apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  namespace: test-a
  annotations:
    kubernetes.io/ingress-bandwidth : 1G
spec:
  containers:
  - image: nginx
    name: nginx-test
  dnsPolicy: ClusterFirst
  restartPolicy: Always
