//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The KubeService-Stack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package webhook

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomItems) DeepCopyInto(out *CustomItems) {
	*out = *in
	out.Ingress = in.Ingress.DeepCopy()
	out.Egress = in.Egress.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomItems.
func (in *CustomItems) DeepCopy() *CustomItems {
	if in == nil {
		return nil
	}
	out := new(CustomItems)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomLimitRange) DeepCopyInto(out *CustomLimitRange) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomLimitRange.
func (in *CustomLimitRange) DeepCopy() *CustomLimitRange {
	if in == nil {
		return nil
	}
	out := new(CustomLimitRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomLimitRange) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomLimitRangeList) DeepCopyInto(out *CustomLimitRangeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomLimitRange, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomLimitRangeList.
func (in *CustomLimitRangeList) DeepCopy() *CustomLimitRangeList {
	if in == nil {
		return nil
	}
	out := new(CustomLimitRangeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomLimitRangeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomLimitRangeSpec) DeepCopyInto(out *CustomLimitRangeSpec) {
	*out = *in
	in.LRange.DeepCopyInto(&out.LRange)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomLimitRangeSpec.
func (in *CustomLimitRangeSpec) DeepCopy() *CustomLimitRangeSpec {
	if in == nil {
		return nil
	}
	out := new(CustomLimitRangeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomLimitRangeStatus) DeepCopyInto(out *CustomLimitRangeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomLimitRangeStatus.
func (in *CustomLimitRangeStatus) DeepCopy() *CustomLimitRangeStatus {
	if in == nil {
		return nil
	}
	out := new(CustomLimitRangeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitRange) DeepCopyInto(out *LimitRange) {
	*out = *in
	in.Max.DeepCopyInto(&out.Max)
	in.Min.DeepCopyInto(&out.Min)
	in.Default.DeepCopyInto(&out.Default)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitRange.
func (in *LimitRange) DeepCopy() *LimitRange {
	if in == nil {
		return nil
	}
	out := new(LimitRange)
	in.DeepCopyInto(out)
	return out
}
