apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-server-cert
  namespace: kube-system
spec:
  dnsNames:
  - customlimitrange-webhook-service.kube-system.svc
  - customlimitrange-webhook-service.kube-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert