kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: customlimitrange-webhook
subjects:
- kind: ServiceAccount
  name: customlimitrange-webhook
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: customlimitrange-webhook
  apiGroup: rbac.authorization.k8s.io