kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: customlimitrange-webhook
  namespace: kube-system
rules:
- apiGroups: ["custom.cmss.com"]
  resources: ["customlimitranges"]
  verbs: ["get"]
