apiVersion: v1
kind: Service
metadata:
  name: customlimitrange-webhook-service
  namespace: kube-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: customlimitrange-webhook
